### ISSUE TITLE
Why it returns fatal error if bitly responses error?

### ISSUE THREAD

**Issue by nimasdj** [hpatoio/bitly-api#20]
If Bitly response has error messages, why it returns fatal error, instead of error message?
It should not throw exception, but just return status and reason data, This is not reasonable! Please use another http than Guzzle!
```
PHP Fatal error:  Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 403
[reason phrase] INVALID_ACCESS_TOKEN
[url] https://api-ssl.bitly.com/v3/user/link_save?access_token=xxxxx&longUrl=http%3A%2F%2Fwww.example.com&title=test in /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Message\Response))
#1 /vendor/symfony/event-dispatcher/EventDispatcher.php(260): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vendor/symfo in /vendor/guzzlehttp/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43
```

Isn't it because of some dependency version mistakes in your json?
Hpatoio version: 2.0.5
Guzzle version: 3.8.1
PHP version: 7.2

**Comment by nimasdj** [comment]
Please read this issue with Guzzle. https://github.com/guzzle/guzzle/issues/2369
Please consider to provide an api to turn of errors.

**Comment by phplicengine** [comment]
Our lib is for Bitly Api v4.
https://github.com/phplicengine/bitly
